---
- name: Install CrowdStrike Falcon Sensor
  hosts: linux
  become: true

  vars:
    falcon_cid: "ADCF014BA51E49728450B4DDB7B42D86-37"

  tasks:

    - name: Copy DEB package to Ubuntu
      copy:
        src: packages/falcon-sensor_7.35.0-18803_amd64.deb
        dest: /tmp/falcon-sensor.deb
      when: ansible_os_family == "Debian"

    - name: Install Falcon Sensor on Ubuntu
      apt:
        deb: /tmp/falcon-sensor.deb
      when: ansible_os_family == "Debian"

    - name: Copy RPM package to Alma/RHEL
      copy:
        src: packages/falcon-sensor-7.35.0-18803.el7.x86_64.rpm
        dest: /tmp/falcon-sensor.rpm
      when: ansible_os_family == "RedHat"

    - name: Install Falcon Sensor on Alma/RHEL
      dnf:
        name: /tmp/falcon-sensor.rpm
        state: present
        disable_gpg_check: true
      when: ansible_os_family == "RedHat"

    - name: Configure Falcon CID
      command: /opt/CrowdStrike/falconctl -s --cid={{ falcon_cid }}
      args:
        creates: /opt/CrowdStrike/cid-configured

    - name: Create marker file
      file:
        path: /opt/CrowdStrike/cid-configured
        state: touch

    - name: Enable Falcon Sensor
      service:
        name: falcon-sensor
        enabled: true
        state: started

    - name: Check Falcon Sensor Status
      command: systemctl status falcon-sensor
      register: falcon_status
      changed_when: false

    - debug:
        var: falcon_status.stdout_lines
